# -*- coding: utf-8 -*-
"""Constructs-practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BiEmLMr4BZlK6sBY--xjmcCtEA-QQRNp
"""

# sequential statements

# Arithenetic operation
x = 100
y = 50
total = x+y
print(total)

# string operation and built in functions
name = 'Muhammad'
length = len(name)
print(length)

upper = name.upper() # changes name to upper case
print(upper)

name1 = 'Muhammad '
name2 = 'Ibrahim'
full_name = name1 + name2 # concatination, used with the '+' sign. it is used to join
full_name

firstchar = full_name[0:8]
print(firstchar)

firs4tchar = full_name[0:4] # extracts letters till 4
print(firs4tchar)

lastchar = full_name[-1] # prints the last character
print(lastchar)

last_3char = full_name[-3:] # prints the last 3character
print(last_3char)

# Conditional statements
#if test expression

a = 10

if a > 7: # colon is used to specify a condition
  print('The value is greater than seven')



# else statement
b = 28

if b > 20:
  print('The value is greater than twenty')
else:
  print('The vaue is  less than twenty')

# pass statement
if a == True:
  pass
else:
  print('This is a false block')

# shorthand conditional statement
c = 30
print('The value is greater than 30') if c > 30  else c == print('The value is less than 30')

x = 10

if x > 0:
  print('Positive')
else:
  print('negative')

# elif
c = 30
if c > 30:
  print('The value is greater than 30') 
elif c == 30:
  print(' The value is equal to 30')  
else:
  print('The value is less than 30')

d = 11
if d % 2 == 0:
  print('This number is even')
elif d % 2 == 1:
  print('This number is odd')
else:
  print('This number is 0')

# Multiple if
a = 100
if a > 0:
  print('This number is positive ')
  if a % 2 == 0:
    print('This number is even too..')
  if a % 2 == 1:
    print('This number is odd too..')
elif a < 0:
  print('the number is zero')
else :
  print('This number is negative')

# and/or operators
test1 = 10
test2 = 8
if test1 > 9 and test2 > 9:
  print('outstanding')
elif test1 <=5 and test2 < 5:
  print('need improvement')
else: 
  print('Very good')

a = 100

if a > 0 and a % 2 == 0:
  print('The number is positive and even')
elif a > 0 and a % 2 == 1:
  print('The number is positive and odd')
elif a < 0 and a % 2 == 0:
  print('The number is negative and even')
elif a < 0 and a % 2 == 1:
  print('The number is negative and odd')
else:
  print('The number is 0')

test = 10
test2 = 5

if test1 >= 5 or test2 >= 5:
  print('Eligible for Final Test')
else:
  print('Better Luck Next Time')

# Multiple terinary operator
a = 100
b = 20
c = 200

max = a if a > b and a > c else b if b > a and b > c else c
print(max)

# Conditional statements in list
fruits = ['Apple', 'Mango', 'Orange']

if 'Apple' in fruits:
  print('Apple is in the lsit')
else:
  print('Apple is not in the list')

if 'Berry' not in fruits:
  fruits.insert(3, "Berry")
  print('fruit inserted')
else:
  pass
print(fruits)

if 'Berry' in fruits:
  fruits.remove('Berry')
  print('fruit removed')
else:
  pass