# -*- coding: utf-8 -*-
"""python-variables- practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zxY_vJgmk0Q5UJyNRraWBpuoQ7mwGhct
"""

print("Muhammad Thinks...")

help()

#storing value
x = 10
print(x)

#mainipulating value
a = x+1
print(a)

# declearing a variable

fruit = "Mango"

print (fruit)

first_name = "Muhammadd Ibrahim Bello"
print(first_name)

# store value/data
#Store strings, boolean , int, float , complex , list data types 

fruit = "Apple"
Flag = True
age = 15
course_code=12.4
complex_no = 1+2j 
fruits = ['apples', 'berry', 'fig']

# finding data type 
# type(fruit)
# type(Flag)
type(age)

# Dynamically_typed data

x = 20
type(x)

x = 28.5
type(x)

# null/empty variable
# moh = (None)
moh = None
type(moh)

# assigning single value to different variables
a=b=c=50

print(c)

# different value to different variables
a,b,c = 27,28,29
print(c-a)
print(a*b)

# data type coversion
x = 28
x=str(x)
type(x)

"""Statements and expressions"""

print(100+250)
print(len('Muhammad Thinks')) # prints length

Ibrahim = "Muhammad "

output = Ibrahim * 5

print(output)

# To get input from user input function
roll=input("Enter Roll Number")
print(roll)