# -*- coding: utf-8 -*-
"""Sets-practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHyW5Fz1v9DemT_0GuZZfC1Qw5qYIgzJ

A set is a data type used to store multiple items in a single variable
"""

# creating set
fruits = {'Apple', 'Oranfe', 'Banana'}
hobbies = set(['Debugging', 'Coding', 'Running', 'Gaming' ])

type(fruits)
type(hobbies)

for i in hobbies:
  print(i)

# adding to set
hobbies.add('Dancing')
print(hobbies)

if "Football" in hobbies:
  print('value present')
else:
  print('value not present')

# removing from set
hobbies.discard('Eating')
hobbies.remove('Dancing')
hobbies.pop() # deletes random item

print(hobbies)

set1 = {'Apple', 'Orange', 'Banan', 'Mango'}
set2 = set(['Papaya', 'Grapes', 'Pineapple', 'Mango'])

Difference = set1 - set2 # whats present in set1 but not in set 2
Difference

set1 = {'Apple', 'Orange', 'Banan', 'Mango'}
set2 = set(['Papaya', 'Grapes', 'Pineapple', 'Mango'])

# intersection
# intersection = set1 & set2
intersection = set1.intersection(set2)
intersection

set1 = {'Apple', 'Orange', 'Banan', 'Mango'}
set2 = set(['Papaya', 'Grapes', 'Pineapple', 'Mango'])

# union
union = set1 | set2
# union = set1.union(set2)
union